version: '3.8'

volumes:
  prometheus_data: {}

services:
  prometheus:
    image: localhost:5000/monitoring/prometheus:v2.50.0
    container_name: prometheus
    restart: unless-stopped
    volumes:
      - type: bind
        source: "/mnt/c/AZ_DATEN/OMS/Workspace/IntelliJ/Monitoring/prometheus/docker/prometheus.yml"
        target: "/etc/prometheus/prometheus.yml"
        read_only: true
      - type: volume #- prometheus_data:/prometheus
        source: prometheus_data
        target: /prometheus
    command:
      - '--config.file=/etc/prometheus/prometheus.yml'
      - '--storage.tsdb.path=/prometheus'
      - '--web.console.libraries=/etc/prometheus/console_libraries'
      - '--web.console.templates=/etc/prometheus/consoles'
      - '--web.enable-lifecycle'
    expose:
      - 9090
    ports:
      - "9090:9090"
    network_mode: bridge
